services:
  rust-app:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    image: rust-app:dev
    command: sleep infinity
    volumes:
      - ..:/workspaces/app/

  swagger-ui:
    image: swaggerapi/swagger-ui
    # environment:
    #   SWAGGER_JSON: /openapi/openapi.json
    # volumes:
    #   - ./openapi:/openapi
    ports:
      - "8081:8080"