services:
  rust-app:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    image: rust-app:dev
    command: sleep infinity
    volumes:
      - ..:/workspaces/app/

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /api-docs/v1.json # Swagger UI が読み込む JSON ファイルのパス
    volumes:
      - ../api-docs:/api-docs # API 定義書の置き場をわかりやすく変更
    ports:
      - "8081:8080"

  swagger-editor:
    image: swaggerapi/swagger-editor
    environment:
      SWAGGER_FILE: /api-docs/v1.json # Swagger UI が読み込む JSON ファイルのパス
    volumes:
      - ../api-docs:/api-docs # API 定義書の置き場をわかりやすく変更
    ports:
      - "8082:8080"